### ISSUE TITLE
jq: command not found

### ISSUE THREAD

**Issue by evoactivity** [NullVoxPopuli/action-setup-pnpm#15]
The action is failing with 

```
Run nullvoxpopuli/action-setup-pnpm@v2
  with:
    no-lockfile: false
  env:
    VOLTA_HOME: /__t/volta/1.1.1/x64
Run if [ ! -f "package.json" ]; then 
/__w/_temp/aa16a0db-e6b1-40d9-abb2-16b87a5a09f3.sh: line 9: jq: command not found
```

This is my workflow

```
on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  server-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.3.0']

    container:
      image: node:latest

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres
        env:
          POSTGRES_USER: arianwellbeing
          POSTGRES_PASSWORD: password
          POSTGRES_DB: arianwellbeing-test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure volta
        uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: wyvox/action-setup-pnpm@v2

      - name: Run tests
        run: node ace test
        working-directory: ./apps/server
        env:
```
